language: python
python:
  - "3.7"
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y zlib1g
  - sudo apt-get install -y openssl
install:
  - make setup-all
  - pipenv install coverage
  - pipenv install codecov
script:
  - python setup.py flake8
  - coverage run setup.py test

after_success:
  - codecov